# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66db9ce0a03f288001bb832e95314fc5490d79074d78829afafba7ba61b59a7252712c899299d014ba7f0a09f17e905ef535c2bbcb79853ade76832a52744c77

test:
  secret_key_base: dee6781596b2c8a3fb855f2e53c5e77cf3b8273c91b846a976283bede279b85bbb53ed48b8cfbbfdd349daeb99a397c97f566a8f7b269c902e70f95f4d8a0609

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
